schema_version: 1

context:
  name: azure-mgmt-netapp
  version: 10.1.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-netapp-${{ version }}.zip
  sha256: 7898964ce0a4d82efd268b64bbd6ca96edef53a1fcd34e215ab5fe87be8c8d03

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.3.2,<2.0
    - isodate >=0.6.1,<1.0

tests:
  - python:
      imports:
        - azure.mgmt.netapp
        - azure.mgmt.netapp.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure NetApp Files Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
