schema_version: 1

context:
  name: azure-mgmt-netapp
  version: 13.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_mgmt_netapp-${{ version }}.tar.gz
  sha256: 4ad08893f94cf9271e2558f0e420f085e83a6af7127a9d556172f08bde945c91

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - isodate >=0.6.1
    - typing_extensions >=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.3.2

tests:
  - python:
      imports:
        - azure.mgmt.netapp
        - azure.mgmt.netapp.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure NetApp Files Management Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
